### ISSUE TITLE
SIGPIPE error using .send() on a socket

### ISSUE THREAD

**Issue by fuzzy** [vlang/v#1373]
**V version:** v0.1.17
**OS:** Linux 5.2.1

**What did you do?**
try to write data to a socket
```
module main

import net
import time

fn sendit(d, h string, p int) {
	sock := net.dial(h, p) or {
		eprintln(err)
		return
	}
	sock.send(d.str, d.len)
	sock.close()
}

fn main() {
	tst_t := time.now()
	tst := tst_t.calc_unix()
	sendit('test.data.string 1 $tst', 'localhost', 2003)
}
```

**What did you expect to see?**
Successful return and exit of the program
 
**What did you see instead?**
through gdb we see a SIGPIPE error:
```$ gdb sockbug  
GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sockbug...
(gdb) r
Starting program: /home/fuzzy/work/devel/vstatd/sockbug 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGPIPE, Broken pipe.
0x00007ffff7e44e2e in send () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff7e44e2e in send () from /usr/lib/libpthread.so.0
#1  0x000055555555b7e4 in net__Socket_send (s=..., buf=0x5555555639c0 "test.data.string 1 1564466649", len=29)
    at .sockbug.c:3529
#2  0x000055555555d470 in sendit (d=..., h=..., p=2003) at .sockbug.c:4171
#3  0x000055555555d541 in main (argc=1, argv=0x7fffffffdcd8) at .sockbug.c:4184```

**Comment by fuzzy** [comment]
The same error happens when using Socket.write() for the record.
```(gdb) bt
#0  0x00007ffff7e44995 in write () from /usr/lib/libpthread.so.0
#1  0x00005555555608ae in net__Socket_write (s=..., str=...) at .vstatd.c:5861
#2  0x00005555555647fa in send_metric (m=..., h=..., p=2003) at .vstatd.c:6894
#3  0x0000555555564d42 in collect_cpu_metrics (t=1564469966, h=..., p=2003) at .vstatd.c:6956
#4  0x0000555555564f86 in executor (f=..., c=...) at .vstatd.c:7031
#5  0x0000555555565c44 in main (argc=3, argv=0x7fffffffdcb8) at .vstatd.c:7188
```

**Comment by fuzzy** [comment]
The methods in the vlib are pretty simple, and seem fine at first glance. Noticed that nothing there explicitly launches any threads, so I'm guessing that this might be in the generated code?

**Comment by kprotty** [comment]
You misspelled "localhost" as "localost"

**Comment by fuzzy** [comment]
If you look at the post history it was originally 'kerplop' which is my local hostname, that had the same behaviour, I just edited the post after the fact to make it 'localhost' and flubbed it

**Comment by fuzzy** [comment]
the behavior is the same with '127.0.0.1' as well just for the record. It's also the same behavior you get if you un-comment all the code in vlib/net/socket_test.v and compile it, then run through gdb.

**Comment by fuzzy** [comment]
I apologize, my recollection of having tried with '127.0.0.1' was faulty. It's using non ipaddr strings that's causing the issue, going with the ip of the service it's not giving me SIGPIPE any longer.

**Comment by medvednikov** [comment]
Good.

But in any case, it should not `SIGPIPE`, but panic. So this should be handled in the socket library.
