### ISSUE TITLE
call_v_from_python example does not work

### ISSUE THREAD

**Issue by tehando** [vlang/v#16112]
```
vmodules: /user_name/.vmodules
vroot: /user_name/v
vexe: /user_name/v/v
vexe mtime: 2022-10-19 13:49:14
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 71bff21.d781396

Git version: git version 2.38.0
Git vroot status: weekly.2022.41-27-gd7813965
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
--------
$ python --version
Python 3.10.8
--------
 platform = Linux-6.0.2-arch1-1-x86_64-with-glibc2.36
```
**What did you do?**
```
[user_name call_v_from_python]$ v -shared test.v
[user_name call_v_from_python]$ python test.py 
```
**What did you expect to see?**
```
call_v_from_python
``` 
**What did you see instead?**
```
[user_name call_v_from_python]$ python test.py 
Traceback (most recent call last):
  File "/home/user_name/v/examples/call_v_from_python/test.py", line 7, in <module>
    lib = CDLL(so_file)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./test.so: undefined symbol: tcc_backtrace
```

**Comment by JalonSolov** [comment]
This works if you add `-cc gcc` to the command line, as in
```
$ v -shared -cc gcc test.v
$ python test.py
lib.square(10) result is 100
$
```
`-cc clang` works as well.  It only fails with the default tcc compiler.

**Comment by spytheman** [comment]
With tcc, you need also: `-d no_backtrace`
```
#0 17:57:49 ᛋ master /v/vnew/examples/call_v_from_python❱v -d no_backtrace -shared test.v 
#0 17:57:50 ᛋ master /v/vnew/examples/call_v_from_python❱python3 test.py 
lib.square(10) result is 100
#0 17:57:51 ᛋ master /v/vnew/examples/call_v_from_python❱
```

**Comment by spytheman** [comment]
I've edited the README.md in this example to mention the `-d no_backtrace` option in V 31adc65 .
