### ISSUE TITLE
parser crash, discovered through radamsa

### ISSUE THREAD

**Issue by spytheman** [vlang/v#22088]
### Describe the bug

Running `v -silent bug5.v` segfaults, due to an overflow that ends with:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000006e04ab in v__parser__Parser_parse_type (p=0x7fffffffb9b0) at /space/v/oo/vlib/v/parser/parse_type.v:492
492             option_pos := p.tok.pos()
(gdb) bt
#0  0x00000000006e04ab in v__parser__Parser_parse_type (p=0x7fffffffb9b0) at /space/v/oo/vlib/v/parser/parse_type.v:492
#1  0x00000000006e56f5 in v__parser__Parser_parse_generic_inst_type (p=0x7fffffffb9b0, name=...) at /space/v/oo/vlib/v/parser/parse_type.v:880
#2  0x00000000006e3aac in v__parser__Parser_parse_any_type (p=0x7fffffffb9b0, language=v__ast__Language__v, is_ptr=0 '\000', check_dot=1 '\001', is_option=0 '\000')
    at /space/v/oo/vlib/v/parser/parse_type.v:786
#3  0x00000000006e0e23 in v__parser__Parser_parse_type (p=0x7fffffffb9b0) at /space/v/oo/vlib/v/parser/parse_type.v:576
#4  0x00000000006e56f5 in v__parser__Parser_parse_generic_inst_type (p=0x7fffffffb9b0, name=...) at /space/v/oo/vlib/v/parser/parse_type.v:880
#5  0x00000000006e3aac in v__parser__Parser_parse_any_type (p=0x7fffffffb9b0, language=v__ast__Language__v, is_ptr=0 '\000', check_dot=1 '\001', is_option=0 '\000')
    at /space/v/oo/vlib/v/parser/parse_type.v:786
#6  0x00000000006e0e23 in v__parser__Parser_parse_type (p=0x7fffffffb9b0) at /space/v/oo/vlib/v/parser/parse_type.v:576
#7  0x00000000006e56f5 in v__parser__Parser_parse_generic_inst_type (p=0x7fffffffb9b0, name=...) at /space/v/oo/vlib/v/parser/parse_type.v:880
#8  0x00000000006e3aac in v__parser__Parser_parse_any_type (p=0x7fffffffb9b0, language=v__ast__Language__v, is_ptr=0 '\000', check_dot=1 '\001', is_option=0 '\000')
    at /space/v/oo/vlib/v/parser/parse_type.v:786
```

### Reproduction Steps

See the attached file, then: `./v -silent bug5.v`, or `./v -g self && gdb --args ./v -silent bug5.v` then inside gdb, `run` and `bt`.

### Expected Behavior

The parser should not segfault, it should just exit with an exit code of 1.

### Current Behavior

The parser segfaults due to an unlimited recursion.

### Possible Solution

The recursion should be limited.

### Additional Information/Context

The bug was discovered after several hours of running `fuzz_v_parser_with_radamsa.sh bug5.v` .

### V version

V 0.4.7 a98a029

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.7 c92577e.a98a029
OS: linux, Ubuntu 20.04.6 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

getwd: /space/v/oo
vexe: /space/v/oo/v
vexe mtime: 2024-08-20 21:10:33

vroot: OK, value: /space/v/oo
VMODULES: OK, value: /home/delian/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.45.2
Git vroot status: weekly.2024.34-14-ga98a0290
.git/config present: true

CC version: cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
```

**Comment by felipensp** [comment]
Where I get bug5.v?

**Comment by JalonSolov** [comment]
Looks like @spytheman forgot to attach it.  :-)

**Comment by spytheman** [comment]
> Where I get bug5.v?

Github refused to upload it, unless it is a .zip or .txt file.

[bug5.v.txt](https://github.com/user-attachments/files/16696331/bug5.v.txt)

**Comment by spytheman** [comment]
Note that it is a bit large - 348KB, the one here <https://github.com/vlang/v/issues/22089> is much smaller (just 4.4KB) and I think it is due to the same cause.

**Comment by spytheman** [comment]
It is fixed by latest V 18f89991efbeea490621a2a961d3b926f6592e8f :

```
#0 15:38:36 ^ master /space/v/oo>./v version
V 0.4.7 18f8999
#0 15:38:40 ^ master /space/v/oo>v -g cmd/tools/measure/parser_speed.v
#0 15:38:46 ^ master /space/v/oo>cmd/tools/measure/parser_speed bug5.v
[cmd/tools/measure/parser_speed.v:19] main.comments_mode: skip_comments
     84664us     117918     353769          1             3      45087   bug5.v
---------------------------------------------------------------------------------------------------------------------------------------------------
        Time     Tokens      Bytes      Lines   Bytes/Token     Errors
---------------------------------------------------------------------------------------------------------------------------------------------------
     84664us     117918     353769          1             3      45087   Parser speed:  4.179 MB/s,       11.8 lines/s,   1 thread(s),     1 files.
#0 15:38:50 ^ master /space/v/oo>v -silent bug5.v
#1 15:38:56 ^ master /space/v/oo>
```
