### ISSUE TITLE
DOS in REPL (and in a file) using '*' or '&' in a function prototype definiton

### ISSUE THREAD

**Issue by bogen85** [vlang/v#2928]
**V version:** V 0.1.23 850788c

**OS:** Linux version 5.3.13-arch1-1

**What did you do?**

Entered **fn dos_me_again(&)** into the REPL...

**What did you expect to see?**
```
>>> fn dos_me_again2(&)
next token = `)`
syntax error: unexpected `&`, expecting `name`
>>>
```
Or some other error message...
 
**What did you see instead?**
```
$ v
V 0.1.23 850788c
Use Ctrl-C or `exit` to exit
>>> fn dos_me_again(&)
sh: line 1: 118744 Segmentation fault      (core dumped) "/home/dwight/v-workspace/v.upstream/v" run .vrepl_temp.v -repl 2>&1
>>> fn dos_me_again(&)
next token = `(`
syntax error: unexpected `dos_me_again`, expecting `(`
>>> 
```
RAM climbed about 12GB before it segfaulted (it hung for a while before segfaulting).

It has the same behavior with **fn dos_me_again(*)** and **fn C.dos_me_again(&)**

Thanks to @donnisnoni95  for finding this DOS.

**Comment by bogen85** [comment]
It also pegged one CPU thread during it's 12GB usage climb.

**Comment by bogen85** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7d078da in __memmove_sse2_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7d078da in __memmove_sse2_unaligned_erms ()
   from /usr/lib/libc.so.6
#1  0x00005555555645fb in array_push (a=0x7fffffffcfa0, val=0x7fffffffcbc0)
    at /home/dwight/v-workspace/v.upstream/vlib/builtin/array.v:241
#2  0x000055555558bbc8 in compiler__Parser_fn_args (p=0x5555557956c0, 
    f=0x7fffffffcf80)
    at /home/dwight/v-workspace/v.upstream/vlib/compiler/fn.v:860
#3  0x00005555555885ff in compiler__Parser_fn_decl (p=0x5555557956c0)
    at /home/dwight/v-workspace/v.upstream/vlib/compiler/fn.v:373
#4  0x00005555555a84d6 in compiler__Parser_parse (p=0x5555557956c0, pass=1)
    at /home/dwight/v-workspace/v.upstream/vlib/compiler/parser.v:456
#5  0x0000555555599867 in compiler__V_parse (v=0x555555600af0, file=..., 
    pass=1) at /home/dwight/v-workspace/v.upstream/vlib/compiler/main.v:183
#6  0x0000555555599af6 in compiler__V_compile (v=0x555555600af0)
    at /home/dwight/v-workspace/v.upstream/vlib/compiler/main.v:218
#7  0x00005555555cfa4e in main__main ()
    at /home/dwight/v-workspace/v.upstream/v.v:113
#8  0x00005555555d12ce in main (argc=2, argv=0x7fffffffe618)
    at /tmp/v/v.tmp.c:55361
(gdb) 
```

**Comment by donnisnoni95** [comment]
fixed by https://github.com/vlang/v/commit/c00a7f3a5e167360e70645a1a99976e7becefbdf

**Comment by bogen85** [comment]
From my initial description:
```
It has the same behavior with fn dos_me_again(*) and fn C.dos_me_again(&)
```

**Comment by bogen85** [comment]
It still segfaults on
```v
fn C.dos_me_again(&)
```

**Comment by bogen85** [comment]
Confirmed fixed for both cases (C. and non C.)
thanks @medvednikov
