### ISSUE TITLE
hashmap crash on OpenBSD (under malloc guard)

### ISSUE THREAD

**Issue by tankf33der** [vlang/v#3347]
XXX: Crash **only** under malloc guard.

**V version:** 
```
# v -v
V 0.1.24 025efcb
```
**OS:** 
```
# uname -a
OpenBSD zaza 6.6 GENERIC#3 amd64
# sysctl -a | grep malloc_conf
vm.malloc_conf=S
```

**What did you do?**
Combine hashmap module and test_rand_strings() from test.

```
# cat hashmap.v
// Copyright (c) 2019 Alexander Medvednikov. All rights reserved.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.
//module hashmap
/*
        This is work in progress.
        A very early test version of the Hashmap with a fixed size.
        Only works with string keys and int values for now.

        I added this to improve performance of the V compiler,
        which uses lots of O(log n) map get's. Turned out with N < 10 000
        the performance gains are basically non-existent.
*/


import rand

struct Hashmap {
        cap           int
        keys          []string
        table         []Hashmapentry
        elm_size      int
pub mut:
        nr_collisions int
}

struct Hashmapentry {
mut:
        key  string
        val  int
        next &Hashmapentry // linked list for collisions
}

const (
        min_cap = 2<<10
        max_cap = 2<<20
)

const(
        fnv64_prime        = 1099511628211
        fnv64_offset_basis = 14695981039346656037
)

const(
    fnv32_offset_basis = u32(2166136261)
    fnv32_prime        = u32(16777619)
)

pub fn new_hashmap(planned_nr_items int) Hashmap {
        mut cap := planned_nr_items * 5
        if cap < min_cap {
                cap = min_cap
        }
        if cap > max_cap {
                cap = max_cap
        }
        return Hashmap{
                cap: cap
                elm_size: 4
                table: make(cap, cap, sizeof(Hashmapentry))
        }
}

pub fn (m mut Hashmap) set(key string, val int) {
        // mut hash := int(b_fabs(key.hash()))
        // idx := hash % m.cap
        idx := int(fnv1a32(key) % m.cap)
        if m.table[idx].key.len != 0 {
                // println('\nset() idx=$idx key="$key" hash="$hash" val=$val')
                m.nr_collisions++
                // println('collision:' + m.table[idx].key)
                mut e := &m.table[idx]
                for e.next != 0 {
                        e = e.next
                }
                e.next = &Hashmapentry{
                        key,val,0}
        }
        else {
                m.table[idx] = Hashmapentry{
                        key,val,0}
        }
}

pub fn (m &Hashmap) get(key string) int {
        // mut hash := int(b_fabs(key.hash()))
        // idx := hash % m.cap
        idx := int(fnv1a32(key) % m.cap)
        mut e := &m.table[idx]
        for e.next != 0 {
                // todo unsafe {
                if e.key == key {
                        return e.val
                }
                e = e.next
        }
        return e.val
}

[inline]
fn b_fabs(v int) f64 {
        return if v < 0 { -v } else { v }
}

// inline functions here for speed
// rather than full impl in vlib
[inline]
fn fnv1a32(data string) u32 {
    mut hash := fnv32_offset_basis
    for i := 0; i < data.len; i++ {
        hash = (hash ^ u32(data[i])) * fnv32_prime
    }
    return hash
}

[inline]
fn fnv1a64(data string) u64 {
    mut hash := fnv64_offset_basis
    for i := 0; i < data.len; i++ {
        hash = (hash ^ u64(data[i])) * fnv64_prime
    }
    return hash
}


fn test_random_strings() {
        mut m := new_hashmap(1000)
        for i in 0..1000 {
                mut buf := []byte
                for j in 0..10 {
                        buf << byte(rand.next(int(`z`) - int(`a`)) + `a`)
                }
                s := string(buf)
                //println(s)
                m.set(s, i)
                assert m.get(s) == i
        }
        m.set('foo', 12)
        val := m.get('foo')
        assert val == 12
}

fn main() {
        test_random_strings()
}
```

```
# ../v -g -verbose build hashmap.v
v    args: ["../v", "-g", "-verbose", "build", "hashmap.v"]
v command: build
v options: ["-g", "-verbose"]
C compiler=cc
["../v", "-g", "-verbose", "build", "hashmap.v"]
all .v files before:
[]
v.module_lookup_paths: ["/root/v/hashmap", "/root/v/hashmap/modules", "/root/v/vlib", "/root/.vmodules"]
v_files_from_dir ("/root/v/vlib/builtin")
v.add_v_files_to_compile > builtin_files: ["/root/v/vlib/builtin/array.v", "/root/v/vlib/builtin/builtin.v", "/root/v/vlib/builtin/builtin_nix.v", "/root/v/vlib/builtin/cfns.v", "/root/v/vlib/builtin/float.v", "/root/v/vlib/builtin/int.v", "/root/v/vlib/builtin/map.v", "/root/v/vlib/builtin/option.v", "/root/v/vlib/builtin/string.v", "/root/v/vlib/builtin/utf8.v"]
get_v_files(hashmap.v)
> just compile one file: "hashmap.v"
user_files: ["hashmap.v"]
  >> trying to find strings in /root/v/hashmap/strings ...
  >> trying to find strings in /root/v/hashmap/modules/strings ...
  >> trying to find strings in /root/v/vlib/strings ...
  << found /root/v/vlib/strings .
v_files_from_dir ("/root/v/vlib/strings")
  >> trying to find strconv in /root/v/hashmap/strconv ...
  >> trying to find strconv in /root/v/hashmap/modules/strconv ...
  >> trying to find strconv in /root/v/vlib/strconv ...
  << found /root/v/vlib/strconv .
v_files_from_dir ("/root/v/vlib/strconv")
  >> trying to find rand in /root/v/hashmap/rand ...
  >> trying to find rand in /root/v/hashmap/modules/rand ...
  >> trying to find rand in /root/v/vlib/rand ...
  << found /root/v/vlib/rand .
v_files_from_dir ("/root/v/vlib/rand")
imports:
["strings", "strconv", "rand"]
all .v files:
["/root/v/vlib/builtin/array.v", "/root/v/vlib/builtin/builtin.v", "/root/v/vlib/builtin/builtin_nix.v", "/root/v/vlib/builtin/cfns.v", "/root/v/vlib/builtin/float.v", "/root/v/vlib/builtin/int.v", "/root/v/vlib/builtin/map.v", "/root/v/vlib/builtin/option.v", "/root/v/vlib/builtin/string.v", "/root/v/vlib/builtin/utf8.v", "/root/v/vlib/strings/builder_c.v", "/root/v/vlib/strings/similarity.v", "/root/v/vlib/strings/strings.v", "/root/v/vlib/strconv/atof.v", "/root/v/vlib/strconv/atoi.v", "/root/v/vlib/rand/pcg32.v", "/root/v/vlib/rand/rand.v", "/root/v/vlib/rand/splitmix64.v", "hashmap.v"]
flags=
cc() isprod=0 outname=hashmap

==========
cc  -std=gnu11 -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-unused-result -Wno-unused-function -Wno-missing-braces -Wno-unused-label -g  -rdynamic  -Werror=implicit-function-declaration -o "hashmap" "/root/.cache/v/hashmap.tmp.c"    -lm -lpthread
cc took 1132 ms
=========
```

**What did you expect to see?**
no crash.
 
**What did you see instead?**
```
# ldd hashmap
hashmap:
        Start            End              Type  Open Ref GrpRef Name
        0000082ad18b0000 0000082ad18cb000 exe   2    0   0      hashmap
        0000082ce2c25000 0000082ce2c54000 rlib  0    1   0      /usr/lib/libm.so.10.1
        0000082d3c155000 0000082d3c162000 rlib  0    1   0      /usr/lib/libpthread.so.26.1
        0000082d8be1e000 0000082d8bf12000 rlib  0    1   0      /usr/lib/libc.so.95.1
        0000082d91c2c000 0000082d91c2c000 ld.so 0    1   0      /usr/libexec/ld.so
# file ./hashmap
./hashmap: ELF 64-bit LSB shared object, x86-64, version 1
# ./hashmap
Segmentation fault (core dumped)
# gdb hashmap hashmap.core
GNU gdb 6.3
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-unknown-openbsd6.6"...
Core was generated by `hashmap'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/lib/libpthread.so.26.1...done.
Loaded symbols for /usr/lib/libpthread.so.26.1
Loaded symbols for /root/v/hashmap/hashmap
Reading symbols from /usr/lib/libm.so.10.1...done.
Loaded symbols for /usr/lib/libm.so.10.1
Symbols already loaded for /usr/lib/libpthread.so.26.1
Reading symbols from /usr/lib/libc.so.95.1...done.
Loaded symbols for /usr/lib/libc.so.95.1
Reading symbols from /usr/libexec/ld.so...Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/libexec/ld.so]
#0  strlen () at /usr/src/lib/libc/arch/amd64/string/strlen.S:125
125     /usr/src/lib/libc/arch/amd64/string/strlen.S: No such file or directory.
        in /usr/src/lib/libc/arch/amd64/string/strlen.S
(gdb) bt
#0  strlen () at /usr/src/lib/libc/arch/amd64/string/strlen.S:125
#1  0x00000389b3e361af in vstrlen (s=0x38c24a4fff0 "avgnjukrry▒▒▒▒▒▒" <Address 0x38c24a50000 out of bounds>) at vlib/builtin/string.v:61
#2  0x00000389b3e32bcc in tos2 (s=0x38c24a4fff0 "avgnjukrry▒▒▒▒▒▒" <Address 0x38c24a50000 out of bounds>) at vlib/builtin/string.v:93
#3  0x00000389b3e41371 in main__test_random_strings () at hashmap.v:134
#4  0x00000389b3e41607 in main__main () at hashmap.v:144
#5  0x00000389b3e418dd in main (argc=1, argv=0x7f7ffffd1a38) at /root/.cache/v/hashmap.tmp.c:10792
Current language:  auto; currently asm
```

**Comment by ka-weihe** [comment]
This file/implementation no longer exists.
