### ISSUE TITLE
WASM 2048 game freezes

### ISSUE THREAD

**Issue by ronkok** [vlang/v#7461]
**OS:** 

Windows 10.

**Browser**

Edge, Chrome, or Firefox

**What did you do?**

I played the 2048 example game.

**What did you expect to see?**

Uninterrupted play.
 
**What did you see instead?**

The game freezes after about 3 minutes of play. Console error message is:

```
abort | @ | index.js:9
Uncaught RuntimeError: abort(OOM). Build with -s ASSERTIONS=1 for more info.
    at abort (https://v2048.vercel.app/index.js:9:16149)
    at abortOnCannotGrowMemory (https://v2048.vercel.app/index.js:9:79870)
    at _emscripten_resize_heap (https://v2048.vercel.app/index.js:9:79963)
    at https://v2048.vercel.app/index.wasm:wasm-function[147]:0x4dc1
    at rb (https://v2048.vercel.app/index.wasm:wasm-function[128]:0x1760)
    at https://v2048.vercel.app/index.wasm:wasm-function[124]:0x6a9
    at https://v2048.vercel.app/index.wasm:wasm-function[323]:0x1fff9
    at https://v2048.vercel.app/index.wasm:wasm-function[333]:0x237e6
    at https://v2048.vercel.app/index.wasm:wasm-function[247]:0x1a624
    at Ob (https://v2048.vercel.app/index.wasm:wasm-function[270]:0x1c18c)
```

Good luck with this language. It looks terrific.

**Comment by spaceface777** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/12110214/102917114-ea2b2500-4484-11eb-9259-1423f7a71eb7.png)

**Comment by ronkok** [comment]
Nice work. The response speed is impressive.
