### ISSUE TITLE
[gg] draw_text segfault

### ISSUE THREAD

**Issue by maciek134** [vlang/v#797]
**V version:** `0.1.9`
**OS:** `Linux *** 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux`

**What did you do?**
```
import gx
import gl
import gg
import glfw
import math
import time
import rand

fn main() {
  glfw.init()

  mut window := glfw.create_window(glfw.WinCfg {
    width: 320,
    height: 320,
    title: 'Hello V!',
  })
  window.make_context_current()

  gg.init()
  mut context := gg.new_context(gg.Cfg {
    width: 320,
    height: 320,
    use_ortho: true,
    font_size: 12,
  })

  for {
    gl.clear_color(255, 255, 255, 255)
    gl.clear()

    context.draw_rect(10, 10, 100, 100, gx.rgb(255, 0, 0))
    context.draw_text(110, 110, 'Hello V!', gx.TextCfg {
      color: gx.Black,
      size: 12,
      align: gx.ALIGN_LEFT,
    })

    window.swap_buffers()

    glfw.wait_events()
    if window.should_close() {
      window.destroy()
      glfw.terminate()
      exit(0)
    }
  }
}
```

**What did you expect to see?**
A `'Hello V!'` text drawn on the GLFW window.
 
**What did you see instead?**
A SIGSEGV:
```
============ running hello ============
create window wnd=0x557feff94880 ptr==(nil)
#version 330 core
layout (location = 0) in vec4 vertex; // <vec2 pos, vec2 tex>
out vec2 TexCoords;

uniform mat4 projection;

void main()
{
    gl_Position = projection * vec4(vertex.xy, 0.0, 1.0);
    TexCoords = vertex.zw;
}  
shader path=simple.vert,
 fpath="simple.frag"
glm ortho(0.000000, 320.000000, 320.000000, 0.000000)
0=0.006250 1=0.000000 2=0.000000 3=0.000000 4=0.000000 5=-0.006250 6=0.000000 7=0.000000 8=0.000000 9=0.000000 10=1.000000 11=0.000000 12=-1.000000 13=1.000000 14=0.000000 15=1.000000 setting o
new gg context VAO=1
shader path=text.vert,
 fpath="text.frag"
glm ortho(0.000000, 320.000000, 0.000000, 320.000000)
new gg text context VAO=2
≈йцукенгшщзхъфывапролджэячсмитьбюЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ
sh: line 1: 16121 Segmentation fault      (core dumped) ./hello 2>&1
```
After debugging I found out that `g_ustring_runes` used in `string.ustring_tmp()` is empty:
```
Program received signal SIGSEGV, Segmentation fault.
ustring_substr (u=..., start=0, end=1) at /home/klh//.vlang//hello.c:2307
2307	 start  =  ( *(int*) array__get( u .runes , start) ) ;
(gdb) p g_ustring_runes
$1 = {data = 0x0, len = 0, cap = 0, element_size = 0}
```
Initializing the array in my code at the top of main:
```
g_ustring_runes = []int
```
kind-of fixes the issue, but then (~may be not connected to that~) I get invalid pointer when trying to close the window:
```
munmap_chunk(): invalid pointer

Program received signal SIGABRT, Aborted.
0x00007ffff7b4c755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7b4c755 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7b37851 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7b8ea38 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff7b9525a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff7b95524 in munmap_chunk () from /usr/lib/libc.so.6
#5  0x00007ffff7be5949 in free_dfa_content () from /usr/lib/libc.so.6
#6  0x00007ffff7bf3105 in regfree () from /usr/lib/libc.so.6
#7  0x00007ffff7e5dbf4 in ?? () from /usr/lib/libglfw.so.3
#8  0x00007ffff7e4a070 in ?? () from /usr/lib/libglfw.so.3
#9  0x000055555557d567 in glfw__terminate () at /home/klh//.vlang//hello.c:4852
#10 0x0000555555581b87 in main (argc=1, argv=0x7fffffffda68) at /home/klh//.vlang//hello.c:7129
```
I'm happy to provide a PR once I figure this out ;p

**EDIT**: more digging required, if I replace `.ustring_tmp()` with `.ustring()` the app exits fine when I close the window.

**Comment by medvednikov** [comment]
Sorry for the ridiculous delay. There will be a better permanent solution, but this works for now.
